# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Relayflow < Formula
  desc "Graph-based agent workflow engine"
  homepage "https://github.com/rajpopat27/relayflow"
  version "0.1.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rajpopat27/relayflow/releases/download/v0.1.2/relayflow_darwin_amd64.tar.gz"
      sha256 "44711723e982ed90223317e289e74d6f12b1ebebe8aade0942a31e9134445a9a"

      define_method(:install) do
        bin.install "relayflow"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rajpopat27/relayflow/releases/download/v0.1.2/relayflow_darwin_arm64.tar.gz"
      sha256 "ea15b6f2d99a629188f737b87407bdb52f91c2353af812f9d1027c5fae306909"

      define_method(:install) do
        bin.install "relayflow"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rajpopat27/relayflow/releases/download/v0.1.2/relayflow_linux_amd64.tar.gz"
      sha256 "7ebb4d5df84fc0906935b4b35dd709450c571782b5f7c9ee8ebaa494e0ddf176"
      define_method(:install) do
        bin.install "relayflow"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rajpopat27/relayflow/releases/download/v0.1.2/relayflow_linux_arm64.tar.gz"
      sha256 "a2d7a8eb3a9946bc636d3d2d9f23ef13df06661c4e5f970c7e06a3a6e8c9fa8d"
      define_method(:install) do
        bin.install "relayflow"
      end
    end
  end

  test do
    system "#{bin}/relayflow", "--help"
  end
end
