# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Relayflow < Formula
  desc "Graph-based agent workflow engine"
  homepage "https://github.com/rajpopat27/relayflow"
  version "0.1.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rajpopat27/relayflow/releases/download/v0.1.2/relayflow_darwin_amd64.tar.gz"
      sha256 "81b021e92801063fd2a80d8a8125ddb57a5d66bd068cf157ae43b908adf80239"

      define_method(:install) do
        bin.install "relayflow"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rajpopat27/relayflow/releases/download/v0.1.2/relayflow_darwin_arm64.tar.gz"
      sha256 "e0e666e50156eadd3c621d2cc17be0aa11b15533d7b2428d9fe7b7e7d58d1f72"

      define_method(:install) do
        bin.install "relayflow"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rajpopat27/relayflow/releases/download/v0.1.2/relayflow_linux_amd64.tar.gz"
      sha256 "9ede480ba7553599c04626a11471b574434b10628ce9a6dfeef4511a726344ba"
      define_method(:install) do
        bin.install "relayflow"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rajpopat27/relayflow/releases/download/v0.1.2/relayflow_linux_arm64.tar.gz"
      sha256 "8e3f2a9fe0c295e9b09194d845e8578213e44bf181178267e78af262300cd402"
      define_method(:install) do
        bin.install "relayflow"
      end
    end
  end

  test do
    system "#{bin}/relayflow", "--help"
  end
end
