# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Relayflow < Formula
  desc "Graph-based agent workflow engine"
  homepage "https://github.com/rajpopat27/relayflow"
  version "0.1.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rajpopat27/relayflow/releases/download/v0.1.2/relayflow_darwin_amd64.tar.gz"
      sha256 "bc31db38b325a390769d68ec93351d2a154bfe14c032a368bca023ff7b68daac"

      define_method(:install) do
        bin.install "relayflow"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rajpopat27/relayflow/releases/download/v0.1.2/relayflow_darwin_arm64.tar.gz"
      sha256 "2a65762fcf775c959729389e7a4fbacb82b4c98521a65528d1cef2476dd0f9a6"

      define_method(:install) do
        bin.install "relayflow"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rajpopat27/relayflow/releases/download/v0.1.2/relayflow_linux_amd64.tar.gz"
      sha256 "45f8b7abecb9f1c33c2d2d136f4ad6aab8a3690bd3e5e8cec65eaa8d5f9ee8b5"
      define_method(:install) do
        bin.install "relayflow"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rajpopat27/relayflow/releases/download/v0.1.2/relayflow_linux_arm64.tar.gz"
      sha256 "21b63185fa7afa9ea6a1e62a07d1d263fc159333d21923fef35cf06c57325a83"
      define_method(:install) do
        bin.install "relayflow"
      end
    end
  end

  test do
    system "#{bin}/relayflow", "--help"
  end
end
