# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RelayFlow < Formula
  desc "Graph-based agent workflow engine"
  homepage "https://github.com/rajpopat27/relay-flow"
  version "0.2.6-alpha"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rajpopat27/relay-flow/releases/download/v0.2.6-alpha/relay-flow_darwin_amd64.tar.gz"
      sha256 "639739e8f449fca554073698e3c3ad403d4c29fb91895717f03282624f50a706"

      define_method(:install) do
        bin.install "relay-flow"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rajpopat27/relay-flow/releases/download/v0.2.6-alpha/relay-flow_darwin_arm64.tar.gz"
      sha256 "103c127e76b9ace0076c7f2babced7e880d9b3dacf00291fe6d2781e0d1cc59c"

      define_method(:install) do
        bin.install "relay-flow"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rajpopat27/relay-flow/releases/download/v0.2.6-alpha/relay-flow_linux_amd64.tar.gz"
      sha256 "828475b98a34aa2de7df3f13fcc11d25ad6dd8b4bc659675f3c67b25ab4dfd26"
      define_method(:install) do
        bin.install "relay-flow"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rajpopat27/relay-flow/releases/download/v0.2.6-alpha/relay-flow_linux_arm64.tar.gz"
      sha256 "1fbfeab2262df4509c633ef1a4cddfe5369069d59633a65c1e702522e7de6401"
      define_method(:install) do
        bin.install "relay-flow"
      end
    end
  end

  test do
    system "#{bin}/relay-flow", "--help"
  end
end
